-- ModAE pricing tables. Run after supabase-setup.sql.
-- This file is safe to re-run and does not delete app_state data.

create table if not exists public.currency_rates (
  currency_code text primary key check (currency_code = upper(currency_code) and length(currency_code) = 3),
  rate_to_inr numeric(18, 6) not null check (rate_to_inr > 0),
  is_active boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by text
);

create table if not exists public.price_lists (
  id bigint generated by default as identity primary key,
  list_code text not null unique,
  supplier_name text not null,
  source_currency text not null check (source_currency = upper(source_currency) and length(source_currency) = 3),
  current_version text,
  uploaded_at date,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by text
);

create table if not exists public.price_list_versions (
  id bigint generated by default as identity primary key,
  price_list_id bigint not null references public.price_lists(id) on delete cascade,
  version_code text not null,
  source_currency text not null check (source_currency = upper(source_currency) and length(source_currency) = 3),
  filename text,
  uploaded_at date,
  is_active boolean not null default false,
  unique (price_list_id, version_code)
);

create table if not exists public.price_list_parts (
  id bigint generated by default as identity primary key,
  version_id bigint not null references public.price_list_versions(id) on delete cascade,
  part_number text not null,
  description text not null,
  unit_price numeric(18, 4) not null check (unit_price >= 0),
  currency text not null check (currency = upper(currency) and length(currency) = 3),
  keywords jsonb not null default '[]'::jsonb,
  unique (version_id, part_number)
);

create table if not exists public.price_list_adders (
  id bigint generated by default as identity primary key,
  part_id bigint not null references public.price_list_parts(id) on delete cascade,
  code text not null,
  description text not null,
  unit_price numeric(18, 4) not null check (unit_price >= 0),
  unique (part_id, code)
);

create index if not exists price_list_parts_number_idx on public.price_list_parts (part_number);
create index if not exists price_list_versions_active_idx on public.price_list_versions (price_list_id, is_active);

insert into public.currency_rates (currency_code, rate_to_inr, updated_by)
values ('INR', 1, 'SYSTEM'), ('EUR', 112, 'SYSTEM'), ('USD', 90, 'SYSTEM')
on conflict (currency_code) do nothing;

-- Backfill pricing data from the legacy JSON slice when it exists. Re-running
-- this block is harmless because all natural keys use ON CONFLICT DO NOTHING.
do $$
declare
  list_row record;
  version_row jsonb;
  v_version_id bigint;
  part_row jsonb;
  v_part_id bigint;
begin
  if to_regclass('public.app_state') is null then return; end if;

  insert into public.currency_rates (currency_code, rate_to_inr, updated_by)
  select upper(item.key), (item.value #>> '{}')::numeric, 'APP_STATE'
  from public.app_state a, jsonb_each(a.value->'currencyRates') item
  where a.key = 'config'
    and item.key <> 'INR'
    and (item.value #>> '{}') ~ '^[0-9]+(\\.[0-9]+)?$'
  on conflict (currency_code) do update set rate_to_inr = excluded.rate_to_inr, updated_by = excluded.updated_by;

  for list_row in
    select item.key as list_code, item.value as list_data
    from public.app_state a, jsonb_each(a.value) item
    where a.key = 'priceLists'
  loop
    insert into public.price_lists (list_code, supplier_name, source_currency, current_version, uploaded_at)
    values (
      list_row.list_code,
      list_row.list_code,
      upper(coalesce(list_row.list_data->>'currency', 'INR')),
      list_row.list_data->>'version',
      nullif(list_row.list_data->>'uploaded', '')::date
    )
    on conflict (list_code) do update set
      supplier_name = excluded.supplier_name,
      source_currency = excluded.source_currency,
      current_version = excluded.current_version,
      uploaded_at = excluded.uploaded_at;

    for version_row in select value from jsonb_array_elements(
      case when jsonb_array_length(coalesce(list_row.list_data->'versions', '[]'::jsonb)) > 0
        then list_row.list_data->'versions'
        else jsonb_build_array(jsonb_build_object(
          'id', list_row.list_code || '-current',
          'version', list_row.list_data->>'version',
          'currency', list_row.list_data->>'currency',
          'uploaded', list_row.list_data->>'uploaded',
          'parts', list_row.list_data->'parts'
        )) end
    ) loop
      insert into public.price_list_versions (price_list_id, version_code, source_currency, filename, uploaded_at, is_active)
      select p.id, coalesce(version_row->>'version', 'Initial'), upper(coalesce(version_row->>'currency', p.source_currency)),
             version_row->>'filename', nullif(version_row->>'uploaded', '')::date,
             coalesce(version_row->>'id', '') = coalesce(list_row.list_data->>'activeVersionId', '')
      from public.price_lists p where p.list_code = list_row.list_code
      on conflict (price_list_id, version_code) do nothing
      returning id into v_version_id;

      if v_version_id is null then
        select v.id into v_version_id
        from public.price_list_versions v join public.price_lists p on p.id = v.price_list_id
        where p.list_code = list_row.list_code and v.version_code = coalesce(version_row->>'version', 'Initial');
      end if;

      for part_row in select value from jsonb_array_elements(coalesce(version_row->'parts', '[]'::jsonb)) loop
        insert into public.price_list_parts (version_id, part_number, description, unit_price, currency, keywords)
        values (v_version_id, part_row->>'pn', coalesce(part_row->>'desc', ''), coalesce((part_row->>'price')::numeric, 0),
                upper(coalesce(part_row->>'currency', version_row->>'currency', list_row.list_data->>'currency', 'INR')),
                coalesce(part_row->'keywords', '[]'::jsonb))
        on conflict (version_id, part_number) do nothing
        returning id into v_part_id;

        if v_part_id is null then
          select p.id into v_part_id from public.price_list_parts p where p.version_id = v_version_id and p.part_number = part_row->>'pn';
        end if;
        insert into public.price_list_adders (part_id, code, description, unit_price)
        select v_part_id, a->>'code', coalesce(a->>'desc', ''), coalesce((a->>'price')::numeric, 0)
        from jsonb_array_elements(coalesce(part_row->'adders', '[]'::jsonb)) a
        on conflict (part_id, code) do nothing;
      end loop;
    end loop;
  end loop;
end $$;

alter table public.currency_rates enable row level security;
alter table public.price_lists enable row level security;
alter table public.price_list_versions enable row level security;
alter table public.price_list_parts enable row level security;
alter table public.price_list_adders enable row level security;

drop policy if exists anon_read_currency_rates on public.currency_rates;
create policy anon_read_currency_rates on public.currency_rates for select to anon, authenticated using (true);
drop policy if exists anon_write_currency_rates on public.currency_rates;
create policy anon_write_currency_rates on public.currency_rates for all to anon, authenticated using (true) with check (true);

do $$
declare t text; begin
  foreach t in array array['price_lists','price_list_versions','price_list_parts','price_list_adders'] loop
    execute format('drop policy if exists anon_read_%1$s on public.%1$I', t);
    execute format('create policy anon_read_%1$s on public.%1$I for select to anon, authenticated using (true)', t);
    execute format('drop policy if exists anon_write_%1$s on public.%1$I', t);
    execute format('create policy anon_write_%1$s on public.%1$I for all to anon, authenticated using (true) with check (true)', t);
    execute format('grant select, insert, update, delete on public.%I to anon, authenticated', t);
  end loop;
end $$;
grant select, insert, update, delete on public.currency_rates to anon, authenticated;
